FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY django-backend/requirements.txt .
RUN pip install -r requirements.txt

# Copy Django code
COPY django_app/ .

# Expose port
EXPOSE 8000

# Run migrations and start server
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]